"use client";
import {redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";import {CalendarDays,ChevronLeft,ChevronRight} from "lucide-react";
import BackButton from "@/app/components/BackButton";
const weekdays=["Lun","Mar","Mer","Gio","Ven","Sab","Dom"];
const labels:Record<string,string>={G:"Giorno",N:"Notte",M1:"M1",M2:"M2",M3:"M3",mp:"Mattino + pomeriggio",RC:"Riposo compensativo",E:"Endoscopia",MRia:"Mattina Rianimazione",GRia:"Guardia Rianimazione",NRia:"Notte Rianimazione",RG:"Reperibilità giorno",RN:"Reperibilità notte",RP:"Reperibilità pomeriggio",SN:"Smonto notte",FT:"Fuori turno"};
function buildCalendar(year:number,month:number){const first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),off=(first.getDay()+6)%7);const cells:(number|null)[]=Array(off).fill(null);for(let d=1;d<=days;d++)cells.push(d);while(cells.length%7)cells.push(null);return cells;}
function dateKey(year:number,month:number,day:number){return String(year)+"-"+String(month+1).padStart(2,"0")+"-"+String(day).padStart(2,"0");}

export default function GeneralShifts(){
 const [current,setCurrent]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});
 const [validated,setValidated]=useState(false),[shifts,setShifts]=useState<any[]>([]),[profiles,setProfiles]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const year=current.getFullYear(),month=current.getMonth();
 useEffect(()=>{(async()=>{setLoading(true);setError("");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Accesso non valido.");setLoading(false);return}const {data:st,error:se}=await s.from("calendar_month_status").select("validated").eq("year",year).eq("month",month+1).maybeSingle();if(se){setError(se.message);setLoading(false);return}setValidated(Boolean(st?.validated));if(st?.validated){const from=String(year)+"-"+String(month+1).padStart(2,"0")+"-01",to=String(year)+"-"+String(month+1).padStart(2,"0")+"-"+String(new Date(year,month+1,0).getDate()).padStart(2,"0");const [{data:rows,error:re},{data:ps,error:pe}]=await Promise.all([s.from("calendar_shifts").select("id,user_id,shift_date,short_name").gte("shift_date",from).lte("shift_date",to).order("shift_date").order("short_name"),s.from("profiles").select("id,username")]);if(re||pe){setError(re?.message||pe?.message||"Errore nel caricamento.");setLoading(false);return}setShifts(rows||[]);setProfiles(Object.fromEntries((ps||[]).map((p:any)=>[p.id,p.username])))}else setShifts([]);setLoading(false)})()},[year,month]);
 const cells=useMemo(()=>buildCalendar(year,month),[year,month]);const byDate=useMemo(()=>shifts.reduce<Record<string,any[]>>((a,x)=>{(a[x.shift_date]??=[]).push(x);return a},{}),[shifts]);
 return <div className="shell"><header className="appbar"><a className="brand" href="/dashboard"><span className="brand-mark"><CalendarDays size={19}/></span>Turni Ospedalieri</a><UserMenu/></header><main className="main"><BackButton/><div className="generation-title-row"><div><p className="eyebrow">Programmazione</p><h1 className="title">Turni generali</h1><p className="sub">Calendario dei turni convalidati del mese.</p></div></div>{error&&<div className="error">{error}</div>}<section className="calendar-card"><div className="calendar-head"><button className="icon-btn" onClick={()=>setCurrent(new Date(year,month-1,1))}><ChevronLeft size={20}/></button><div style={{textAlign:"center"}}><p className="eyebrow" style={{margin:0}}>{year}</p><h2>{new Intl.DateTimeFormat("it-IT",{month:"long"}).format(current).replace(/^./,x=>x.toUpperCase())}</h2></div><button className="icon-btn" onClick={()=>setCurrent(new Date(year,month+1,1))}><ChevronRight size={20}/></button></div>{loading?<p className="muted" style={{marginTop:18}}>Caricamento…</p>:!validated?<div className="card" style={{marginTop:18,textAlign:"center"}}><h2 style={{marginTop:0}}>Turni non ancora convalidati</h2><p className="muted">Il calendario di questo mese sarà visibile qui dopo la convalida da parte dell'amministrazione.</p></div>:<div className="calendar" style={{marginTop:18}}>{weekdays.map(d=><div className="dow" key={d}>{d}</div>)}{cells.map((day,i)=>!day?<div className="day empty" key={i}/>:<div className="day" key={i}><div className="date">{day}</div><div className="cell-shifts">{(byDate[dateKey(year,month,day)]||[]).map(x=><div className="calendar-shift-chip" key={x.id}><strong>{x.short_name}</strong> <span>{profiles[x.user_id]||"—"}</span></div>)}</div></div>)}</div>}</section></main></div>;
}
