CREATE TABLE IF NOT EXISTS public.gettonista_availability (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  availability_date date NOT NULL,
  cause text NOT NULL CHECK (cause IN ('giorno','mattina','pomeriggio','notte')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, availability_date, cause)
);
ALTER TABLE public.gettonista_availability ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gettonista_availability TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.gettonista_availability_id_seq TO authenticated;

CREATE POLICY gettonista_availability_select_own_or_admin ON public.gettonista_availability
FOR SELECT TO authenticated
USING (user_id = auth.uid() OR public.get_my_role() IN ('admin','super_admin'));

CREATE POLICY gettonista_availability_insert_own ON public.gettonista_availability
FOR INSERT TO authenticated
WITH CHECK (
  user_id = auth.uid()
  AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.employment_role = 'gettonista')
);

CREATE POLICY gettonista_availability_update_own ON public.gettonista_availability
FOR UPDATE TO authenticated
USING (user_id = auth.uid() AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.employment_role = 'gettonista'))
WITH CHECK (user_id = auth.uid() AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.employment_role = 'gettonista'));

CREATE POLICY gettonista_availability_delete_own ON public.gettonista_availability
FOR DELETE TO authenticated
USING (user_id = auth.uid() AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.employment_role = 'gettonista'));
